n = input('Digite um algo:')
print('O tipo primitivo deste valor é:',type(n))
print('Só tem espaços?', n.isspace())
print('É um número?', n.isnumeric())
print('É alfabético?', n.isalpha())
print('É alfanumérico?', n.isalnum())
print('É maiúsculo?', n.isupper())
print('É minúsculo?', n.islower())
print('É capitalizada?', n.istitle())
