nome1 = str(input("Produto 1: "))
nome2 = str(input("Produto 2: "))
preço1 = float(input("Valor do Produto 1: "))
preço2 = float(input("Valor do Produto 2: "))
#soma = (nome1 + nome2)
total = ((nome1 + nome2) * (20/100))
print("O produto", nome1, "que custa", preço1, "custara", preço1 * 0.20 , "com 20% de desconto")
print("O produto", nome2, "que custa", preço2, "custava", preço2 * 0.20, "com 20% de desconto")
print("O valor total da compra na forma líquida é: ",soma)
print("O valor total da compra na forma Bruta é: ",total)
